/// Flutter icons CostumIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CostumIcons
///      fonts:
///       - asset: fonts/CostumIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CostumIcons {
  CostumIcons._();

  static const _kFontFam = 'CostumIcons';
  static const String? _kFontPkg = null;

  static const IconData book = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData claass = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData student = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData course = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
